#!/bin/bash

top -bn1 | grep "Cpu(s)" | \
           sed "s/.*, *\([0-9.]*\)%* id.*/\1/" | \
           awk '{print 100 - $1"%"}'

case $BLOCK_BUTTON in
    1) x=`ps axch -o cmd:15,%cpu --sort=-%cpu | head`
       notify-send -u low "<span font='18px'>cpu:<b></b></span>" "<span font='18px'>$x<b></b></span>"
    ;;
esac


