#!/bin/bash
# Copyright (C) 2014 Alexander Keller <github@nycroth.com>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

#------------------------------------------------------------------------

INTERFACE="${BLOCK_INSTANCE:-wlan0}"

wifi_name=`nmcli connection show |egrep -e "wifi.*wlp2s0" |cut -d" " -f1`

#------------------------------------------------------------------------

# As per #36 -- It is transparent: e.g. if the machine has no battery or wireless
# connection (think desktop), the corresponding block should not be displayed.
[[ ! -d /sys/class/net/${INTERFACE}/wireless ]] ||
    [[ "$(cat /sys/class/net/$INTERFACE/operstate)" = 'down' ]] && exit

#------------------------------------------------------------------------

QUALITY=$(grep $INTERFACE /proc/net/wireless | awk '{ print int($3 * 100 / 70) }')

#------------------------------------------------------------------------

echo $wifi_name $QUALITY% # full text
echo $wifi_name $QUALITY% # short text

$my_color="#248f24"
# color
if [[ $QUALITY -ge 80 ]]; then
    echo "$my_color"
elif [[ $QUALITY -lt 80 ]]; then
    echo "$my_color"
elif [[ $QUALITY -lt 60 ]]; then
    echo "$my_color"
elif [[ $QUALITY -lt 40 ]]; then
    echo "$my_color"
fi


# 2) this=`nmcli connection show |egrep -e "wifi.*wlp2s0" |cut -d" " -f1`
#     notify-send -t 3000 -u low "wifi:  $this"

case $BLOCK_BUTTON in
    # 1) bash ~/.scripts/ping_echo.sh 
    #     ;;
    2)bash ~/.scripts/net/connect_wifi
        ;;

    3)bash ~/.scripts/net/connect_vpn
        ;;
    # 3) nmcli connection down $wifi_name \
    #     && notify-send -u low "disconnect to wifi"
    #     ;;
esac
