#!/bin/sh

# mute system
~/.scripts/mute_system.sh

pic=~/.config/lock_screen.png

BLANK='#bb355e3b'
CLEAR='#bb355e3b'
DEFAULT='#FFFFFF'
TEXT='#FFFFFF'
WRONG='#b22222'
VERIFYING='#bb00bbbb'

i3lock \
	--insidever-color=$CLEAR \
	--ringver-color=$VERIFYING \
	--insidewrong-color=$CLEAR \
	--ringwrong-color=$WRONG \
	--inside-color=$BLANK \
	--ring-color=$DEFAULT \
	--line-color=$BLANK \
	--separator-color=$DEFAULT \
	--verif-color=$TEXT \
	--wrong-color=$TEXT \
	--time-color=$TEXT \
	--date-color=$TEXT \
	--layout-color=$TEXT \
	--keyhl-color=$WRONG \
	--bshl-color=$WRONG \
	--screen 1 \
	--clock \
	--indicator \
	--time-str="%I:%M %p" \
	--date-str="%A, %m %Y" \
	--keylayout 1 \
	-i $pic -L

# --blur 5                     \
