#!/usr/bin/env bash

# exit when have less than 1 arguments
if [[ $# -lt 1 ]] || [[ $1 == '-h' ]]; then
	echo -e "Usage:"
	echo -e "\t$(basename $0) {target_name} [dir_name] [search_type]"
	exit 1
fi

target_name=$1

if [[ $# -eq 2 ]]; then
	dir_name=$1
elif [[ $# -eq 3 ]]; then
	dir_name=$2
fi

# f - file, d - directory
if [ "$3" ]; then
	search_type=$3
else
	search_type=f
fi

mkdir -v "$dir_name" 2>/dev/null

# find files/directories and move them to the directory
find -maxdepth 1 -iname "*$target_name*" -type $search_type |
	xargs -I{} mv -v {} "$dir_name" 2>/dev/null
